version: '3.7'

services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/client'
      - '/client/node_modules'
    environment:
      - NODE_ENV=development
    
  nginx:
    # restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '3000:80'

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /api/node_modules
      - ./api:/api




  